### PR TITLE
Use ChaincodeStubInterface

### PR DESCRIPTION
**Pull request by brad-gorman**
If we ever merge in the new ChaincodeStubInterface, this change is needed for Jenkins to pass.

Signed-off-by: Bradley Gorman <bgorman@au1.ibm.com>

### CODE REVIEW

**Comment by brad-gorman** [comment]
Signed-off-by: Bradley Gorman <bgorman@au1.ibm.com>

**Comment by JonathanLevi** [comment]
Hi @brad-gorman, I believe the system currently requires the sign-off in the following form:
Signed-off-by: FIRST LAST < EMAIL >

**Comment by brad-gorman** [comment]
@JonathanLevi that is what I wrote - the angle brackets were stripped by the comment. Or should I be using the spaces between the angle brackets?

**Comment by brad-gorman** [comment]
@JonathanLevi I think this can be merged now. The ChaincodeStubInterface got merged into fabric.

I've got a review on Gerrit to swap fabric back to this repo as well: https://gerrit.hyperledger.org/r/#/c/811/

**Pull request merged**
